### ISSUE TITLE
Add BBPWorkshop 2024 page

### ISSUE THREAD

**Issue by 3design** [3design/bbp#271]
- [x] Add main page with youtube links
- [x] Add gallery page

**Comment by 3design** [comment]
@SusanneWenzel @pjtoussaint : missing title for workshop. Can you please tell me what the title was for this workshop?

**Comment by SusanneWenzel** [comment]
8th BigBrain Workshop 2024
Challenges of Multimodal Data Integration

**Comment by 3design** [comment]
- [ ] Alter card on news and index page to link to 2024 page

**Comment by SusanneWenzel** [comment]
- Please update logos in the footer :)
- Please enlarge text in the header to fit the font size in the text below (Featured) or v.vs
- Please add somewhere the link to the event's website: https://go.fzj.de/BigBrainWorkshop2024 
- Link to the gallery is a bit hidden, can that be more prominent or directly embedded?
-  YT Links broken:
BigBrain Project Educational Lecture (HBHL Training Day)
Indirect network disconnection methods (HBHL Training Day)
Sulcal morphometry for multiple subjects using BrainVisa / Morphologist (HBHL Training Day)
The BigMac Dataset: combining multi-contrast MRI and microscopy in the macaque brain (HBHL Training Day)
Integrating AI approaches for brain modelling (HBHL Training Day)

- Making the multiscale organization of the human brain accessible to reproducible workflows using siibra-python (HBHL Training Day)
Hands-on session by Timo Dickscheid
==> Timo Dickscheid & Sebastian Bludau


YT descriptions
- Please add names of keynote speakers to the headline, or below, such that it is visible at first glance without expanding the text
- Sievers Lecture: Michel Thiebaut de Schötten --> Michel Thiebaut de Schotten

**Comment by 3design** [comment]
@SusanneWenzel the broken YT links were the videos you just revised. I have replaced them on youtube and put in the new link for the webpage

**Comment by 3design** [comment]
@SusanneWenzel I've made the changes and you can preview them https://3design.github.io/bbp/bigbrainworkshop-2024.html

I wasn't too sure about 
- Please enlarge text in the header to fit the font size in the text below (Featured) or v.vs
I think you were asking me to alter the font sizes on the slides in the 'featured' section, so I reduced the headline and name font sizes

**Comment by SusanneWenzel** [comment]
@3design Its still somehow unbalanced. The featured list looks huge compared to the text above. I mean the Headline and short description in the Header Image. 
Also (at least on a large screen) headline and short description look a bit lost in front of the large image. But I agree, this becomes better when making the browser window smaller. Maybe you can find a compromise.
Maybe reduce the images of the speakers and in the featured list and enlarge the text a bit in the header?

[] de Schötten --> de Schotten typo is also on our website

**Comment by SusanneWenzel** [comment]
@3design Thank you! Looks good now
