### ISSUE TITLE
Add new featured paper, Alex Oberstrass

### ISSUE THREAD

**Issue by SusanneWenzel** [3design/bbp#273]
Please add a new featured paper.
Text and image here:  https://drive.google.com/open?id=12lm4OykLVP8oI4h28S_oyfGqPmaB54ED&usp=drive_fs

**Comment by 3design** [comment]
@SusanneWenzel I have updated the site. There is a card on the index page and the featured page. The featured paper itself is [here](https://3design.github.io/bbp/featured-paper-8.html)

**Comment by SusanneWenzel** [comment]
@3design I changed a few things myself. Please have a look.

**Comment by 3design** [comment]
@SusanneWenzel Looks great! I'm happy with the results
